miniQ/urls.py
from django.contrib import admin
from django.urls import path, include
from quora import views
from django.conf.urls import handler404,handler500

urlpatterns = [
    path('index/', include('quora.urls')),
    path('admin/', admin.site.urls),
]

handler404 = 'quora.views.handler404'
handler500 = 'quora.views.handler500'

quora/urls.py
from django.urls import path

from . import views

app_name = 'quora'

urlpatterns = [
    path('', views.home, name='home'),
    path('register/', views.index, name='index'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('all_questions/', views.all_questions, name='all_questions'),
    path('ask_a_question/', views.addquestion, name='add'),
    path('all_question/', views.individual_questions, name='individual_questions'),
    path('all_answers/', views.individual_answers, name='individual_answers'),
    path('all_upvoted_answers/', views.individual_upvoted, name='individual_upvoted'),
    path('question_answered/', views.addanswer, name='addanswer'),
    path('all_answers/<int:qid>', views.all_answers, name='all_answers'),
    path('highest_upvoted_question/', views.past_hour_highest_votes,
         name='past_hour_highest_votes'),
    path('highest_upvoted_question_ever/', views.highest_upvoted_question,
         name='highest_upvoted_question'),
    path('highest_upvoted_answer/', views.past_hour_highest_votes_answer,
         name='past_hour_highest_votes_answer'),
    path('highest_upvoted_answer_ever/', views.highest_upvoted_answer,
         name='highest_upvoted_answer'),
    path('ajax/send_votes/', views.ans_upvotes, name='ans_upvotes'),
    path('ajax/send_upvoters_list/', views.see_all_upvoters, name='see_all_upvoters')
]

quora/models.py
from django.db import models

# Create your models here.


class User(models.Model):

    fname = models.CharField(max_length=80)
    lname = models.CharField(max_length=80)
    email = models.EmailField(unique=True)
    password = models.CharField(max_length=200)


class Question(models.Model):

    question = models.TextField()
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    total_upvotes = models.IntegerField(default=0)
    date = models.DateTimeField(auto_now_add=True)

    # def __str__(self):
    #     return self.question


class Answers(models.Model):

    answer = models.TextField()
    question_id = models.ForeignKey(Question, on_delete=models.CASCADE)
    answer_upvotes = models.IntegerField(default=0)
    ans_date = models.DateTimeField(auto_now_add=True)
    user_id = models.ForeignKey(User, on_delete=models.CASCADE)


class Upvotes(models.Model):

    upvoted_user = models.ForeignKey(User, on_delete=models.CASCADE)
    upvoted_answer = models.ForeignKey(Answers, on_delete=models.CASCADE)
    vote_date = models.DateTimeField(auto_now_add=False)

quora/forms.py
from django import forms

from quora.random_string_generator import random_string_generator_c
from .models import User, Question, Answers


class SignupForm(forms.Form):

    fname = forms.CharField(label="First Name", required=True)
    lname = forms.CharField(label="Last Name", required=True)
    email = forms.EmailField(required=True)
    password = forms.CharField(label="Password", required=True)
    repassword = forms.CharField(label="Re-type Password", required=True)

    class Meta:
        model = User

    def clean_email(self):
         email = self.cleaned_data.get('email')
         try:
             match = User.objects.get(email=email)
         except User.DoesNotExist:
            # Unable to find a user, this is fine
            return email
         raise forms.ValidationError('This email address is already in use.')

    def clean_repassword(self):
        psw = self.cleaned_data.get('password')
        repsw = self.cleaned_data.get('repassword')
        if psw != repsw:
            raise forms.ValidationError("Password doesn't match!")
        return self.cleaned_data


class LoginForm(forms.Form):

    username = forms.CharField(label="Email/Username", required=True)
    password = forms.CharField(label="Password", required=True)

    class Meta:
        model = User

    def clean(self):
        username = self.cleaned_data.get('username')
        password = self.cleaned_data.get('password')
        ranstrng = random_string_generator_c()
        userpasw = ranstrng.hash_password(password)

        try:
            user = User.objects.get(email=username)
            if user.password != userpasw:
                raise forms.ValidationError("Sorry, wrong username or password !")
        except User.DoesNotExist:
                raise forms.ValidationError("Invalid Login")
        return self.cleaned_data


class QuestionForm(forms.Form):

    question = forms.CharField(label="What's on your mind", required=True)

    class Meta:
        model = Question


class AnswerForm(forms.Form):

    answer = forms.CharField(label="", required=True)

    class Meta:
        model = Answers

# widget = forms.Textarea(attrs={'width': "100%", 'cols': "80", 'rows': "20", })

quora/views.py
import datetime
from django.http import JsonResponse
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse

from quora.decorators import myuser_login_required
from quora.random_string_generator import random_string_generator_c
from .forms import SignupForm, LoginForm, QuestionForm, AnswerForm
from .models import User, Question, Answers, Upvotes

# Create your views here.


def index(request):
    if 'user_id' in request.session:
        return HttpResponseRedirect(reverse('quora:home'))
    else:

        if request.method == 'POST':
            form = SignupForm(request.POST)
            if form.is_valid():
                user = User()
                user.fname = form.cleaned_data['fname'].strip()
                user.lname = form.cleaned_data['lname'].strip()
                user.email = form.cleaned_data['email'].strip()
                uspw = form.cleaned_data['password'].strip()
                ranstr = random_string_generator_c()
                userpasw = ranstr.hash_password(uspw)
                user.password = userpasw
                user.save()
                return HttpResponseRedirect(reverse('quora:login'))
                # return render(request, 'quora/base.html', {'user': user})
            else:
                return render(request, 'quora/register.html', {'form': form})
        else:
            form = SignupForm()
        return render(request, 'quora/register.html', {'form': form})


def login(request):

    if 'user_id' in request.session:
        return HttpResponseRedirect(reverse('quora:home'))
    elif request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            user = User.objects.get(email=request.POST['username'])
            request.session['user_id'] = user.id
            return HttpResponseRedirect(reverse('quora:home'))
    else:
        form = LoginForm()
    return render(request, 'quora/login.html', {'form': form})


@myuser_login_required
def logout(request):
        try:
            del request.session['user_id']
        except KeyError:
            pass
        return HttpResponseRedirect(reverse('quora:home'))


@myuser_login_required
def addquestion(request):

    if request.method == 'POST':
        form = QuestionForm(request.POST)
        if form.is_valid():
            question_ip = form.cleaned_data['question'].strip()
            question_text = " ".join(question_ip.split())
            print(question_text)
            userid = request.session['user_id']
            user = User.objects.get(pk=userid)
            question = Question(question=question_text, user=user)
            question.save()
            return HttpResponseRedirect(reverse('quora:home'))
    else:
        form = QuestionForm()
    return render(request, 'quora/question.html', {'form': form})


@myuser_login_required
def addanswer(request):

    questions = Question.objects.order_by('-date')
    if request.method == 'POST':
        form = AnswerForm(request.POST)
        if form.is_valid():
            answer_ip = form.cleaned_data['answer'].strip()
            ques_id = request.POST.get('xyz')
            question = Question.objects.get(pk=ques_id)
            answer_text = " ".join(answer_ip.split())
            userid = request.session['user_id']
            user = User.objects.get(pk=userid)
            answer = Answers(answer=answer_text, question_id=question,
                             user_id=user)
            answer.save()
            return HttpResponseRedirect(reverse('quora:home'))
    else:
        form = AnswerForm()
    args = {
        'questions': questions,
        'form': form
    }
    return render(request, 'quora/questionList.html', args)


def home(request):
    questions = Question.objects.order_by('-date')
    return render(request, 'quora/dashboard.html', {'questions': questions})


def all_questions(request):
    questions = Question.objects.order_by('-date')
    args= {
        'all_que': True,
        'questions': questions
    }
    return render(request, 'quora/dashboard.html', args)


def all_answers(request, qid):

    question = Question.objects.get(pk=qid)
    answer_list = question.answers_set.all()
    args = {
            'answer_list': answer_list,
            'question': question
        }
    return render(request, 'quora/allanswers.html', args)


@myuser_login_required
def individual_questions(request):
    userid = request.session['user_id']
    user = User.objects.get(pk=userid)
    questions = Question.objects.filter(user=user)
    args = {
            'questions': questions,
         }
    # print(questions)
    return render(request, 'quora/individual_ques.html', args)


@myuser_login_required
def individual_answers(request):
    userid = request.session['user_id']
    user = User.objects.get(pk=userid)
    answers = Answers.objects.filter(user_id=user)
    args = {
            'answers': answers,
         }
        # print(questions)
    return render(request, 'quora/individual_ans.html', args)


def ans_upvotes(request):
    if 'user_id' in request.session:
        userid = request.session['user_id']
        user = User.objects.get(pk=userid)
        ansid = request.GET.get('ansid', None)
        answer = Answers.objects.get(pk=ansid)
        is_voted = Upvotes.objects.filter(upvoted_user=user,
                                          upvoted_answer=answer).exists()
        if is_voted is False:
            answer.answer_upvotes += 1
            answer.save()
            send_upvotes = answer.answer_upvotes
            question = Question.objects.get(pk=answer.question_id.id)
            # print(question)
            question.total_upvotes += 1
            question.save()
            now = datetime.datetime.now()
            upvotes = Upvotes(upvoted_user=user, upvoted_answer=answer, vote_date=now)
            upvotes.save()
        data = {
                'is_voted': is_voted,
                }
        if data['is_voted']:
            data['error_message'] = 'You have already upvoted this answer!'
        else:
            data['upvotes'] = send_upvotes
    else:
        data = {
            'not_loggedin': True,
            'notify':  'You have to log in to upvote any answer!'
        }
    # print(data)
    return JsonResponse(data)


@myuser_login_required
def individual_upvoted(request):
    userid = request.session['user_id']
    user = User.objects.get(pk=userid)
    upvotes = Upvotes.objects.filter(upvoted_user=user)
    args = {
            'upvotes': upvotes,
            'individual': True,
         }
    # print(questions)
    return render(request, 'quora/individual_ans.html', args)


def past_hour_highest_votes(request):

    past_one_hour = True
    now = datetime.datetime.now()
    then = now-datetime.timedelta(hours=1)
    votes = Upvotes.objects.filter(vote_date__range=[then, now])
    dict_ans = {}
    for vote in votes:
        if vote.upvoted_answer.question_id in dict_ans:
            dict_ans[vote.upvoted_answer.question_id] += 1
        else:
            dict_ans[vote.upvoted_answer.question_id] = 1
    max = 0
    qun_id = None
    # print(votes)
    for i in dict_ans:
        if dict_ans[i] > max:
            max = dict_ans[i]
            qun_id = i

    args= {
        'qun_id': qun_id,
        'past_one_hour': past_one_hour
    }
    return render(request, 'quora/highest_upvotes.html', args)


def highest_upvoted_question(request):
    questions = Question.objects.all()
    max_votes = 0
    qun_id = None
    for qun in questions:
        if qun.total_upvotes > max_votes:
            max_votes = qun.total_upvotes
            qun_id = qun
    args = {
        'qun_id': qun_id,
    }
    return render(request, 'quora/highest_upvotes.html', args)


def past_hour_highest_votes_answer(request):
    past_one_hour = True
    now = datetime.datetime.now()
    then = now - datetime.timedelta(hours=1)
    votes = Upvotes.objects.filter(vote_date__range=[then, now])
    dict_ans = {}
    for vote in votes:
        if vote.upvoted_answer in dict_ans:
            dict_ans[vote.upvoted_answer]+=1
        else:
            dict_ans[vote.upvoted_answer] = 1
    ans_id = None
    max = 0
    for i in dict_ans:
        if dict_ans[i] > max:
            max = dict_ans[i]
            ans_id = i

    args = {
        'ans_id': ans_id,
        'past_one_hour': past_one_hour
    }
    return render(request, 'quora/highest_upvotes_answer.html', args)


def highest_upvoted_answer(request):
    answers = Answers.objects.all()
    max_votes = 0
    ans_id = None
    for qun in answers:
        if qun.answer_upvotes > max_votes:
            max_votes = qun.answer_upvotes
            ans_id = qun
    args = {
        'ans_id': ans_id,
    }
    return render(request, 'quora/highest_upvotes_answer.html', args)


def see_all_upvoters(request):
    ansid = request.GET.get('ansid', None)
    answer = Answers.objects.get(pk=ansid)
    upvotes = Upvotes.objects.filter(upvoted_answer=answer)
    upvoters = []
    for i in upvotes:
        upvoters.append(i.upvoted_user.fname + " " + i.upvoted_user.lname)
    data = {
        'upvoters': upvoters
    }
    return JsonResponse(data)


def handler404(request):
    return render(request, 'quora/error_404.html', status=404)


def handler500(request):
    return render(request, 'quora/error_500.html', status=500)

quora/templates/quora/allanswers.html
{% extends 'quora/base.html' %}

{% block stylesheet %}
<style>
.well {margin-bottom:0px;margin-top:20px;border-radius:0;border:0.5px none;background-color:#FFFFFF}
.list-group > li {margin-bottom: 10px;border:0 none}
.round {
    display: inline-block;
    height: 30px;
    width: 30px;
    line-height: 30px;
    -moz-border-radius: 15px;
    border-radius: 15px;
    background-color: #222;
    color: #FFF;
    text-align: center;
    margin-right:15px;
}
.round.blue {
    background-color: #3EA6CE;
}

</style>

{% endblock %}
{% block javascript %}
<script type="text/javascript">
$(function () {
  // Delegating to `document` just in case.
  $(document).on("hidden.bs.modal", "#myModal", function () {
    $(this).find("#yui").html(""); // Just clear the contents.
  });
});
$(document).ready(function()
{

    $(".btn").click(function()
    {

    var ansid = $(this).attr("id");
    if (ansid.indexOf('a') > -1)
    {
        newansid = ansid.substring(3);
        $.ajax({
        url: '{% url 'quora:see_all_upvoters' %}',
        type: 'get',
        data: {
          'ansid': newansid
        },
        dataType: 'json',
        success: function (data) {
               <!--console.log(ansid);-->
          $.each(data.upvoters, function (index, upvote) {
                $('.modal-body').append('<li>' + upvote + '</li>');
            })
            <!--$('.modal-body').text(data.upvoters);-->

            $('#myModal').modal('show');
        },
        error: function(data){
            alert('server error');
        }
        });
    }
    else
    {

        $.ajax({
        url: '{% url 'quora:ans_upvotes' %}',
        type: 'get',
        data: {
          'ansid': ansid
        },
        dataType: 'json',
        success: function (data) {
        if(data.not_loggedin)
        {
                    alert(data.notify);
        }
        else if(data.is_voted){
                alert(data.error_message);
        }
        else
        {
                console.log(ansid);
            var a = ansid+"_upvote";
            var b = ansid+"_ab"
            console.log(a);
          $("#"+a).html(data.upvotes);
          $("#"+b).css("color","orangered");

        }

        }
      });

    }


    });

});
    </script>
{% endblock %}

{% block content %}
<div class="container-fluid">
    <h3 style="word-wrap: break-word;"><strong>{{question.question}}</strong></h3>
    <h4 class="text-info">(Total upvotes - {{question.total_upvotes}})</h4>
    <!--<h3>{{quest}}</strong></h3>-->
    <div id="myModal" class="modal fade" role="dialog">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                    <h5 class="modal-title">All Upvoters</h5>
                </div>
                <div class="modal-body" id="yui">
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-primary" data-dismiss="modal">Close</button>
                </div>
            </div>
        </div>
    </div>


<ul class="list-group">
        {% if answer_list %}
            {%  for answer in answer_list %}
    <div class="well well-sm"><div class="round blue"><span class="glyphicon glyphicon-user"></span></div><strong>{{answer.user_id.fname}} {{answer.user_id.lname}}</strong>
        <p><small style="font-size:12px;margin-left:45px">Answered on {{answer.ans_date.date}}</small></p></div>
            <li class="list-group-item"><p class="text-justify" style="word-wrap: break-word;text-align: justify;text-justify: inter-word;
                                text-indent:1cm;">{{answer.answer}}</p></li>
                <button  style="align-right" id="{{answer.id}}" type="button" class="btn btn-default" ><span id="{{answer.id}}_ab" class="glyphicon glyphicon-arrow-up"></span>
                    Upvote <span id="{{answer.id}}_upvote" style="color:red;padding-left:15px;"> <strong>{{answer.answer_upvotes}}</strong></span></button>
                <button  style="align-right" id="abc{{answer.id}}" type="button" class="btn btn-default" >
                    see all upvoters </button>
            {% endfor %}
        {% else %}
            <div  align="center" class="panel panel-default">This question has no answers</div>
        {% endif %}
  </ul>
</div>
{% endblock %}

quora/templates/quora/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <title>{% block head %}Bootstrap Example{% endblock %}</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
     {% block javascript %} {% endblock %}
  <style>
  body {padding-top: 90px;}
 .navbar-brand {height:70px; padding:25px;font-size:30px;font-family: "Arial Black", Gadget, sans-serif;}
  .navbar-nav > li > a {padding-top:25px !important; padding-bottom:25px !important;}
.navbar {min-height:70px !important}
 <!--.form-control {width:100%}-->
  </style>
    {% block stylesheet %}{% endblock %}
</head>
<body>

<nav class="navbar  navbar-default navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <a class="navbar-brand"><strong style="color:#191970;">mini-Quora</strong></a>
    </div>
    <ul class="nav navbar-nav">
        <!--{% with url_name=request.resolver_match.url_name %}-->
      <li class="{% if request.resolver_match.view_name == 'quora:home' %}active{% endif %}"><a href="{% url 'quora:home' %}">Home</a></li>
      <li class="{% if request.resolver_match.view_name == 'quora:add' %}active{% endif %}"><a href="{% url 'quora:add' %}">Ask a Question</a></li>
      <li class="{% if request.resolver_match.view_name == 'quora:addanswer' %}active{% endif %}"><a href="{% url 'quora:addanswer'  %}">Answer a Question</a></li>
    <!--{% endwith %}-->
    </ul>
    <ul class="nav navbar-nav navbar-right">
        {% if  logged_in %}
        <li><a><span class="glyphicon glyphicon-user"></span> Hey {{ user.fname }}</a></li>
      <li><a href="{% url 'quora:logout' %}"><span class="glyphicon glyphicon-log-out"></span> Logout</a></li>
    </ul>
      {% else %}
      </ul>
        <ul class="nav navbar-nav navbar-right">
      <li><a href="{% url 'quora:index' %}"><span class="glyphicon glyphicon-user"></span> Sign Up</a></li>
      <li><a href="{% url 'quora:login' %}"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
    </ul>
      {% endif %}
  </div>
</nav>
<div class="container">
  <div class="row">
    <nav class="col-sm-3">
      <ul class="nav nav-pills nav-stacked" data-spy="affix">
          {% if  logged_in %}
          <li class="{% if request.resolver_match.view_name == 'quora:all_questions' %}active{% endif %}"><a href="{% url 'quora:all_questions' %}">All Questions</a></li>
          <li class="{% if request.resolver_match.view_name == 'quora:individual_questions' %}active{% endif %}"><a href="{% url 'quora:individual_questions' %}">My Questions</a></li>
          <li class="{% if request.resolver_match.view_name == 'quora:individual_answers' %}active{% endif %}"><a href="{% url 'quora:individual_answers' %}">My Answers</a></li>
          <li class="{% if request.resolver_match.view_name == 'quora:individual_upvoted' %}active{% endif %}"><a href="{% url 'quora:individual_upvoted' %}">Upvoted by me</a></li>
          <li class="{% if request.resolver_match.view_name == 'quora:past_hour_highest_votes' %}active{% endif %}"><a href="{% url 'quora:past_hour_highest_votes' %}" >Highest upvoted question over past hour</a></li>
          <li class="{% if request.resolver_match.view_name == 'quora:highest_upvoted_question' %}active{% endif %}"><a href="{% url 'quora:highest_upvoted_question'  %}">Highest upvoted question ever</a></li>
          <li class="{% if request.resolver_match.view_name == 'quora:past_hour_highest_votes_answer' %}active{% endif %}"><a href="{% url 'quora:past_hour_highest_votes_answer'  %}" >Highest upvoted answer over past hour</a></li>
          <li class="{% if request.resolver_match.view_name == 'quora:highest_upvoted_answer' %}active{% endif %}"><a href="{% url 'quora:highest_upvoted_answer'  %}">Highest upvoted answer ever</a></li>
          {% else %}
                    <li class="{% if request.resolver_match.view_name == 'quora:all_questions' %}active{% endif %}"><a href="{% url 'quora:all_questions' %}">All Questions</a></li>
            <li class="{% if request.resolver_match.view_name == 'quora:past_hour_highest_votes' %}active{% endif %}"><a href="{% url 'quora:past_hour_highest_votes' %}">Highest upvoted question over past hour</a></li>
          <li class="{% if request.resolver_match.view_name == 'quora:highest_upvoted_question' %}active{% endif %}"><a href="{% url 'quora:highest_upvoted_question'  %}">Highest upvoted question ever</a></li>
          <li class="{% if request.resolver_match.view_name == 'quora:past_hour_highest_votes_answer' %}active{% endif %}"><a href="{% url 'quora:past_hour_highest_votes_answer'  %}" >Highest upvoted answer over past hour</a></li>
          <li class="{% if request.resolver_match.view_name == 'quora:highest_upvoted_answer' %}active{% endif %}"><a href="{% url 'quora:highest_upvoted_answer'  %}">Highest upvoted answer ever</a></li>

          {% endif %}
      </ul>
    </nav>

        <div class="col-sm-9">

            {% block content %}
            {% endblock %}
  </div>
  </div>

</div>
</body>
</html>

quora/templates/quora/dashboard.html
{% extends 'quora/base.html' %}

{% block stylesheet %}
<style>
.panel-default > .panel-heading {background-color:#ffffff;padding-top:5px;padding-bottom:5px;}
.panel-body {padding-top:8px;padding-bottom:5px;}
.panel-footer {background-color:#ffffff}
.round {
    display: inline-block;
    height: 30px;
    width: 30px;
    line-height: 30px;
    -moz-border-radius: 15px;
    border-radius: 15px;
    background-color: #222;
    color: #FFF;
    text-align: center;
    margin-right:15px;
}
<!--.round.round-lg {-->
    <!--height: 40px;-->
    <!--width: 40px;-->
    <!--line-height: 40px;-->
    <!-- -moz-border-radius: 20px;-->
    <!--border-radius: 20px;-->
    <!--font-size: 1.5em;-->
<!--}-->
.round.blue {
    background-color: #3EA6CE;
}
</style>

{% endblock %}

{% block content %}
    <div class="panel-group">
     {% if questions %}
           {% if all_que %}
                {%  for question in questions %}

                    {% if question.answers_set.all %}
                        <div class="panel panel-default">
                            <div class="panel-heading"><h4><strong style="word-wrap: break-word;"><a href="{% url 'quora:all_answers' qid=question.id %}">{{question.question}}</a></strong></h4></div>
                                {%  for answer in question.answers_set.all|slice:":1" %}
                            <div class="panel-body"><div class="round blue"><span class="glyphicon glyphicon-user"></span></div><strong>{{answer.user_id.fname}}  {{answer.user_id.lname}}</strong></div>
                                        <div class="panel-body"><p class="text-justify" style="word-wrap: break-word;text-align: justify;text-justify: inter-word;text-indent:2cm;">{{answer.answer}}</p></div>
                                {% endfor %}
                                <!--<div class="panel-footer">Published on {{question.date}} </div>-->
                         </div>
                    {% else %}

                                <div class="panel panel-default">
                                    <div class="panel-heading"><h4><strong style="word-wrap: break-word;"><a href="{% url 'quora:all_answers' qid=question.id %}">{{question.question}}</a></strong></h4></div>
                                                <div class="panel-body"><p  align="center" class="lead">This question has no answers yet</p></div>
                                    <!--<div class="panel-footer">Published on {{question.date}}</div>-->
                                 </div>
                    {% endif %}
                {% endfor %}
            {% else %}

                {%  for question in questions %}
                    {% if question.answers_set.all %}
                        <div class="panel panel-default">
                            <div class="panel-heading"><h4><strong style="word-wrap: break-word;"><a href="{% url 'quora:all_answers' qid=question.id %}">{{question.question}}</a></strong></h4></div>
                            {%  for answer in question.answers_set.all|slice:":1" %}
                            <div class="panel-body"><div class="round blue"><span class="glyphicon glyphicon-user"></span></div><strong>{{answer.user_id.fname}}  {{answer.user_id.lname}}</strong></div>
                                    <div class="panel-body"><p class="text-justify" style="word-wrap: break-word;text-align: justify;text-justify: inter-word;text-indent:2cm;">{{answer.answer}}</p></div>
                            {% endfor %}
                            <!--<div class="panel-footer">Published on {{question.date}}</div>-->
                        </div>
                    {% endif %}
                {% endfor %}
            {% endif %}


     {% else %}
        <h3 class="text-info" class="font-weight-bold">No questions have been asked on this website yet <span style="color:red"> :(<</span></h3>
        <h3 class="bg-success" class="font-weight-bold"><a href="{% url 'quora:add' %}">Be the first one</a></h3>

     {% endif %}
        </div>

{% endblock %}

quora/templates/quora/error_404.html
<html>
<h2>404</h2>
</html>

quora/templates/quora/individual_ans.html
{% extends 'quora/base.html' %}



{% block content %}
    {% if individual %}
        {%  for upvote in upvotes %}

             <div class="page-header">
                 <h3 class="text-info" class="font-weight-bold"><a href="{% url 'quora:all_answers' qid=upvote.upvoted_answer.question_id.id   %}">{{upvote.upvoted_answer.question_id.question}}</a></h3>
            </div>
            <li class="list-group-item" ><p class="text-justify" style="word-wrap: break-word;text-align: justify;text-justify: inter-word;
                        text-indent:1cm;">{{upvote.upvoted_answer.answer}}</p></li>
<li class="list-group-item" ><span style="color:blue;margin-right:550px"> <strong>Upvoted By You</strong></span><span>
    <strong>Answered By {{upvote.upvoted_answer.user_id.fname}}</strong></span></li>

        {% endfor %}


    {% else %}

        {%  if answers %}
            {%  for answer in answers %}

             <div class="page-header">
                 <h3 class="text-info" class="font-weight-bold"><a href="{% url 'quora:all_answers' qid=answer.question_id.id   %}">{{answer.question_id.question}}</a></h3>
            </div>
            <li class="list-group-item" ><p class="text-justify" style="word-wrap: break-word;text-align: justify;text-justify: inter-word;
                        text-indent:1cm;">{{answer.answer}}</p></li>

            {% endfor %}
        {% else %}
                  <h3 class="text-info" align="center" class="font-weight-bold">You haven't answered any answers yet  :(<</h3>
        {% endif %}

    {% endif %}
{% endblock %}